import "UserData.idl";

namespace BiBi
{
    runtimeclass UserDataViewModel 
    {
        UserDataViewModel();
        
        UserData UserData{ get; };
        Windows.Foundation.Collections.IObservableMap<String, UserData> UserList{ get; };
    }
}
