namespace BiBi
{
    
    runtimeclass UserData : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserData();
        String UserId;
        String Username;
        String Addr;
        String Avatar;
    }
}
